# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间
alarm_timed: '13:00'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语，双语）
# 3 : 土味情话
dictum_channel: 1

girlfriend_infos:
  -
    #女友微信昵称
    wechat_name: 'Coco cui'
    #女友所在桂林
    city_name: '青岛'
    # 从那天开始勾搭的（可空）
    start_date: '2016-01-24'
    # 短句的最后留言（可空）
    sweet_words: ''